# Generated by Django 3.2.16 on 2022-11-27 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_energy_in_watt', models.IntegerField()),
                ('consumed_energy_in_watt', models.IntegerField()),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
