# Generated by Django 3.2.16 on 2022-11-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pannello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='reportData',
        ),
    ]
