# Generated by Django 3.2.16 on 2022-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannello', '0002_rename_post_reportdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='consumed_energy_in_watt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='produced_energy_in_watt',
            field=models.IntegerField(null=True),
        ),
    ]
