# Generated by Django 3.2.16 on 2022-12-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannello', '0003_auto_20221130_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
